Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Exemples
objet1 = [-3, 1] # Objet ou image en x=-3 de taille y=1
lentille1 = [2, -1] # Lentilles en x=2 de distance focale f=-1
print(objet[0])  # Quelle valeur est affichee ? A quelle grandeur physique correspond-elle ?
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-fa64bfd7138e>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mobjet1[0m [0;34m=[0m [0;34m[[0m[0;34m-[0m[0;36m3[0m[0;34m,[0m [0;36m1[0m[0;34m][0m [0;31m# Objet ou image en x=-3 de taille y=1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mlentille1[0m [0;34m=[0m [0;34m[[0m[0;36m2[0m[0;34m,[0m [0;34m-[0m[0;36m1[0m[0;34m][0m [0;31m# Lentilles en x=2 de distance focale f=-1[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mprint[0m[0;34m([0m[0mobjet[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m  [0;31m# Quelle valeur est affichee ? A quelle grandeur physique correspond-elle ?[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'objet' is not defined
NameError: name 'objet' is not defined

